#!/usr/bin/python                                                                                 
                                                                                
from perfsonar_basic_probe import *

#sys.path.insert(0, '.')                      
class PerfsonarEsmondProbe(PerfsonarSimpleProbe):
    """
    Probe that reads from a perfsonar and posts it to an esmond central data store
    """
    def __init__(self):
        PerfsonarSimpleProbe.__init__(self)
        self.metricName = "org.osg.general.perfsonar-simple"
        metric = rsvprobe.RSVMetric("Perfsonar-Monitor",
                                    self.metricName, rsvprobe.RSVMetric.STATUS)
        self.supported_metrics = [metric]
        # the default values                                                        
        # username for uploading ifnormation to the goc                            
        self.username = "afitz"
        # key for uploading information to the goc                                  
        self.key = "fc077a6a133b22618172bbb50a1d3104a23b2050"
        # The goc_url is the url for where to upload the data                       
        self.goc_url = "http://osgnetds.grid.iu.edu"
        # Add the options so the parsing knows what to expect                       
        self.addopt("", "username=", "--username username the username for uploading data to the goc")
        self.addopt("", "key=", "--key key the key for uploading data to the goc")
        self.addopt("", "goc=", "--goc url the url for where to upload the data (i.e http://osgnetds.grid.iu.edu)")
    
    def parseopt(self):
        """
        Parse options speficic to this probe
        """
        options, optlist, remainder = PerfsonarSimpleProbe.parseopt(self)
        for opt, arg in options:
            if opt == '--username':
                self.username = arg
            elif opt == '--key':
                self.key = arg
            elif opt == '--goc':
                self.goc_url = arg
        return options, optlist, remainder

def main():
    probe = PerfsonarEsmondProbe()
    return probe.run()

if __name__ == '__main__':
    sys.exit(main())
    
