#!/usr/bin/python
#import perfsonar_simple_local_probe
#import perfsonar_basic_probe
from perfsonar_basic_probe import *

#sys.path.insert(0, '.')
class PerfsonarActiveMQSimpleProbe(PerfsonarSimpleProbe):
    """
    TODO - write description of the probe
    """
    def __init__(self):
        PerfsonarSimpleProbe.__init__(self)
        self.metricName = "org.osg.general.perfsonar-activemq-simple"
        metric = rsvprobe.RSVMetric("Perfsonar-Monitor",
                                    self.metricName, rsvprobe.RSVMetric.STATUS)
        self.supported_metrics = [metric]
        self.allowedMQEvents = self.allowedEvents
        self.maxMQmessageSize = 10000
        self.directoryqueue = None
        # These ones are for the active MQ probe                                                  
        self.addopt("", "allowedMQEvents=", "--allowedMQEvents a list with the allowed event types")
        self.addopt("", 'directoryqueue=', "--directoryqueue a dir for stompctl")
        self.addopt("", 'mq-max-message-size=', "--mq-max-message-size the size in KB of the biggest message allowed in the Mq")
        
    def parseopt(self):
        options, optlist, remainder = PerfsonarSimpleProbe.parseopt(self)
        for opt, arg in options:
            if opt == '--directoryqueue':
                self.directoryqueue = arg
            elif opt == '--allowedMQEvents':
                self.allowedMQEvents = arg.replace(" ", '')
            elif opt == '--mq-max-message-size':
                self.maxMQmessageSize = arg        
                # If alloedMQEvents is not defined in the opts use allowedEvents                                                                                                                
        if '--allowedMQEvents' not in optlist:
            self.allowedMQEvents = self.allowedEvents
        return options, optlist, remainder
        
def main():
    probe = PerfsonarActiveMQSimpleProbe()
    return probe.run()

if __name__ == '__main__':
    sys.exit(main())
